# Cloudtype의 무료 플랜의 경우 매일 03시~09시 사이에 서버가 자동으로 중지됩니다. 
#이 워크플로우는 매일 한국시간 07시와 09시에 서버를 깨우도록 설정되어 있습니다. 
#또한, 수동으로도 실행할 수 있도록 workflow_dispatch 이벤트도 포함되어 있습니다.

name: Wake up Cloudtype Server

on:
  schedule:
    - cron: '5 22,0 * * *'
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: fastjjune/kimjunyoung/kimjunyoung
          stage: main
          yaml: |
            name: kimjunyoung
            app: java-springboot
            options:
              git:
                branch: main
                url: https://github.com/${{ github.repository }}.git
              install: ./gradlew bootJar
              start: java -Dserver.port=$PORT -jar build/libs/app.jar
              ports: 8080