# Cloudtype의 무료 플랜의 경우 매일 03시~09시 사이에 서버가 자동으로 중지됩니다. 
#이 워크플로우는 매일 한국시간 07시와 09시에 서버를 깨우도록 설정되어 있습니다. 
#또한, 수동으로도 실행할 수 있도록 workflow_dispatch 이벤트도 포함되어 있습니다.

name: Wake up Cloudtype Server

on:
  schedule:
    - cron: '5 22,0 * * *'
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Wake backend with HTTP request
        run: |
          curl --fail --silent --show-error \
            --location \
            --retry 5 \
            --retry-delay 10 \
            --retry-all-errors \
            --max-time 120 \
            https://port-0-kimjunyoung-mp46398g3f283d23.sel3.cloudtype.app/actuator/health \
            > /dev/null